import numpy as np
from pathlib import Path
import time
import sys

import tflite_runtime.interpreter as tflite
from nfstream import NFStreamer


# =========== #
# =  PATHS  = #
# =========== #
BASE_PATH = Path("/home/Detection_M5LLM")
MODEL_PATH = BASE_PATH / "dos_classifier.tflite"
MEAN_PATH = BASE_PATH / "mean.npy"
SCALE_PATH = BASE_PATH / "scale.npy"
FEATURES_PATH = BASE_PATH / "features.npy"


# ================ #
# =  PARAMETERS  = #
# ================ #
try:
    INTERPRETER = tflite.Interpreter(model_path=str(MODEL_PATH))
    INTERPRETER.allocate_tensors()

    INPUT_DETAILS = INTERPRETER.get_input_details()
    OUTPUT_DETAILS = INTERPRETER.get_output_details()

    MEAN = np.load(MEAN_PATH).astype(np.float32)
    SCALE = np.load(SCALE_PATH).astype(np.float32)
    FEATURES = list(np.load(FEATURES_PATH, allow_pickle=True))

except FileNotFoundError as e:
    print(f"[ERROR] Archivo de modelo o parámetros no encontrado: {e}")
    sys.exit(1)

except Exception as e:
    print(f"[ERROR] Error al inicializar el entorno: {e}")
    sys.exit(1)


# =============== #
# =  FUNCTIONS  = #
# =============== #
def preprocess_flow(flow) -> np.ndarray:
    """
    Convert a captured network flow into a normalized feature vector suitable for inference.

    This function extracts the ordered list of features used during training, 
    builds a numerical feature vector from the NFStreamer flow object and applies 
    the same StandardScaler normalization parameters that were computed during training.
    Missing attributes in the flow object are replaced with zero in
    order to preserve the expected input dimensionality.

    :param flow: Network flow object generated by NFStreamer containing statistical traffic features.
    :type flow: nfstream.flow.Flow
    :return: Normalized feature array with shape (1, n_features).
    :rtype: numpy.ndarray
    :raises TypeError: If the provided flow object is None.
    """
    if flow is None:
        raise TypeError("El objeto flow recibido no puede ser None.")
    
    values = []

    for feature in FEATURES:
        if hasattr(flow, feature):
            value = getattr(flow, feature)
        else:
            value = 0
        values.append(value)

    X = np.array([values], dtype=np.float32)
    X = (X - MEAN) / SCALE

    return X


def classify_flow(flow) -> None:
    """
    Perform inference on a single network flow and print the classification result.

    The function preprocesses the flow, feeds the resulting feature vector into the loaded 
    interpreter and retrieves the predicted probability score.
    The output is interpreted as the probability of a DoS attack. If the score is greater than 0.5, 
    the flow is labeled as "DoS ATTACK"; otherwise it is labeled as "BENIGN".

    :param flow: Network flow object generated by NFStreamer.
    :type flow: nfstream.flow.Flow
    :raises ValueError: Handled internally. Generated during preprocessing if formatting or mathematical errors occur.
    :raises Exception: Handled internally. Catches any unexpected runtime errors during TFLite inference.
    """
    try:
        X = preprocess_flow(flow)

        INTERPRETER.set_tensor(INPUT_DETAILS[0]['index'], X)
        INTERPRETER.invoke()

        prediction = INTERPRETER.get_tensor(OUTPUT_DETAILS[0]['index'])[0][0]
        label = "DoS ATTACK" if prediction > 0.5 else "BENIGN"

        print(f"[{time.strftime('%H:%M:%S')}] "
              f"{flow.src_ip}:{flow.src_port} -> {flow.dst_ip}:{flow.dst_port} "
              f"| Score: {prediction:.4f} | {label}")

    except ValueError as e:
        print(f"[WARNING] Flujo descartado por error de formato: {e}")

    except Exception as e:
        print(f"[ERROR] Error al clasificar flujo: {e}")


def main() -> None:
    """
    Execute the real-time DoS detection pipeline on live network traffic.

    This function initializes the NFStreamer capture engine on the specified
    network interface, enables statistical feature extraction, and continuously
    processes each generated flow if its destination is the devices's IP.

    For every captured flow, the system:
        - Extracts statistical traffic features.
        - Applies the same preprocessing used during training.
        - Performs inference using the TensorFlow Lite model.
        - Prints the timestamped classification result to the console.

    The process runs indefinitely until manually interrupted.
    """
    print("[INFO] Iniciando captura con NFStream...")
    
    streamer = NFStreamer(
        source="wlan0",
        statistical_analysis=True,
        idle_timeout=10,
        active_timeout=30
    )

    try:
        for flow in streamer:
            if flow.dst_ip == "10.180.100.136":
                classify_flow(flow)

    except Exception as e:
        print(f"[ERROR] Error durante la clasificación: {e}")

if __name__ == "__main__":
    main()