import argparse
import logging
import csv
import time
import sys
import joblib
import requests
import pandas as pd
import numpy as np
from nfstream import NFStreamer

# ================ #
# =  PARAMETERS  = #
# ================ #
parser = argparse.ArgumentParser()
parser.add_argument('--model', required=True)
parser.add_argument('--features', required=True)
parser.add_argument('--ip', required=True)
parser.add_argument('--webhook', required=True)
parser.add_argument('--log', required=True)
parser.add_argument('--results', required=True)
args = parser.parse_args()

logging.basicConfig(filename=args.log, level=logging.INFO, format='%(asctime)s [%(levelname)s] %(message)s')

try:
    MODEL = joblib.load(args.model)
    FEATURES = list(np.load(args.features, allow_pickle=True))
except Exception as e:
    logging.error(f"Archivo de modelo o parámetros no encontrado: {e}")
    sys.exit(1)

with open(args.results, 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(["timestamp", "src_ip", "dst_ip", "score", "label", "latency"])

# =============== #
# =  FUNCTIONS  = #
# =============== #
def preprocess_flow(flow) -> pd.DataFrame:
    """
    Convert a captured network flow into a DataFrame suitable for inference.

    This function extracts the ordered list of features used during training
    and builds a DataFrame. Missing attributes are replaced with zero.

    :param flow: Network flow object generated by NFStreamer.
    :type flow: nfstream.flow.Flow
    :return: DataFrame with shape (1, n_features).
    :rtype: pandas.DataFrame
    """
    values = [getattr(flow, feature, 0) for feature in FEATURES]
    return pd.DataFrame([values], columns=FEATURES)

def classify_flow(flow):
    """
    Perform inference on a single network flow and print the classification result.
    Uses the Random Forest model loaded via joblib.
    The output is interpreted as the probability of a DoS attack. If the score is greater than 0.5, 
    the flow is labeled as "DoS ATTACK"; otherwise it is labeled as "BENIGN".

    :param flow: Network flow object generated by NFStreamer.
    :type flow: nfstream.flow.Flow
    :raises ValueError: Handled internally. Generated during preprocessing if formatting or mathematical errors occur.
    :raises Exception: Handled internally. Catches any unexpected runtime errors during inference.
    """
    try:
        start_time = time.time()
        X = preprocess_flow(flow)
        
        probabilities = MODEL.predict_proba(X)[0]
        prediction = probabilities[1] if len(probabilities) > 1 else probabilities[0]
        label = "DoS ATTACK" if prediction > 0.5 else "BENIGN"
        
        latency = time.time() - start_time
        
        with open(args.results, 'a', newline='') as f:
            writer = csv.writer(f)
            writer.writerow([time.time(), flow.src_ip, flow.dst_ip, prediction, label, latency])
        
        if label == "DoS ATTACK":
            try:
                requests.post(args.webhook, json={"device_ip": args.ip, "src": flow.src_ip, "score": float(prediction)}, timeout=1)
            except requests.exceptions.RequestException as e:
                logging.warning(f"No se pudo enviar alarma a la web: {e}")

    except Exception as e:
        logging.error(f"Error al clasificar flujo: {e}")

def main():
    """
    Execute the real-time DoS detection pipeline on live network traffic.

    This function initializes the NFStreamer capture engine on the specified
    network interface, enables statistical feature extraction, and continuously
    processes each generated flow if its destination is the devices's IP.

    For every captured flow, the system:
        - Extracts statistical traffic features.
        - Applies the same preprocessing used during training.
        - Performs inference using the RandomForest model.
        - Prints the timestamped classification result to the console.

    The process runs indefinitely until manually interrupted.
    """
    logging.info("Iniciando captura con NFStream...")

    streamer = NFStreamer(source="wlan0", statistical_analysis=True, idle_timeout=10, active_timeout=30)
    
    try:
        for flow in streamer:
            if flow.dst_ip == args.ip:
                classify_flow(flow)
    except Exception as e:
        logging.error(f"Error durante la clasificación: {e}")

if __name__ == "__main__":
    main()